modules/es-extensions/publisher/configs/publisher-tenant.json

Fix the G-reg 5.0.0 SNAPSHOT server start up issue related to an unterminated string literal.

fix the unterminated string literal error when server startup

---

modules/distribution/src/main/assembly/bin.xml

In bin.xml, application-authentication framework related config had hard coded kernel snapshot version.
Replaced it with version property.

Correct the hardcoded kernel version

---

modules/es-extensions/publisher/asset/service/asset.js

When updating a service created without a wsdl url, a 'ResourceNotFoundExceptionResourceNotFoundException' was thrown in BE.
This was due to , trying to log wsdluuid in the update method. When there is no wsdl, it gives that exception.
Thus, removed the line.

fix ResourceNotFoundException when updating a service

---

modules/distribution/src/main/assembly/bin.xml
modules/es-extensions/publisher/extensions/app/greg_publisher/app.js

with the fix[1], created our own app extension to enabel showing 'service' & 'wsdl' extansions in the publisher & disabled default assets coming from ES (document,provider,site,gadget).
Updated the bin.xml to copy it to necessary location.
[1]https://github.com/wso2/product-es/pull/144

add new app extension to enable service & wsdl estensions

---

modules/distribution/src/main/assembly/bin.xml

G-Reg pack didnt have 'claim-config.xml' file in repository/conf .  It resulted giving an exception
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Claim handling failed!
org.wso2.carbon.identity.application.authentication.framework.exception.FrameworkException(Intermittent)
Thus, copied it in bin.xml.
Likewise copied email-admin-config.xml & identity-mgt.properties file to our pack.

update bin.xml to copy security related files

---

modules/es-extensions/publisher/extensions/app/greg_impact/modules/dataPopulator.js
modules/es-extensions/publisher/extensions/app/greg_impact/pages/index.jag

changing impact analysis, dependency graph to use resource paths instead of artifact.path

Changing the way nodes are tracked in dependency graph

---

modules/samples/asset-models/ApplicationModel/pom.xml
modules/samples/asset-models/BusinessProcessModel/pom.xml
modules/samples/asset-models/PeopleModel/pom.xml
modules/samples/asset-models/ProjectModel/pom.xml
modules/samples/asset-models/TestPlanModel/pom.xml
modules/samples/pom.xml

Also asset model samples were added to the general product build to ensure sample are built before packing.
Reason for these sample's failure is setting of \<scope\>test\</scope\> for dependency org.wso2.carbon.reporting.util on product-greg main pom.xml.
Due to this scope set asset model samples which require \<scope\>compile\</scope\> fails when building.
According to maven documentation [2] "Furthermore, those dependencies are propagated to dependent projects". Therefore we have to restate scope if the scope is changed in a parent pom.xml file.
[1] https://wso2.org/jira/browse/REGISTRY-2115
[2] https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

fixing stand alone building of asset modle samples - REGISTRY-2115

---

modules/es-extensions/publisher/extensions/app/greg_impact/modules/dataPopulator.js
modules/es-extensions/publisher/extensions/app/greg_impact/pages/index.jag

With this change depth of dependency graph (longest path from dependency graph root to its farthest child) can be restricted.
By adding \<dependencyGraphMaxDepth\>{depth-value}\</dependencyGraphMaxDepth\> in to \<wso2registry\> of registry.xml  user can control the depth of the graph.
If **dependencyGraphMaxDepth element is not set** in registry.xml, dependency graph will be created **without any restriction on depth**. Also if **dependencyGraphMaxDepth is set to a negative value, dependency graph will be created without any restriction on depth**.
1. dependencyGraphMaxDepth = 0, means only source node will be displayed in dependency graph.
2. dependencyGraphMaxDepth = 1, means only source node and its immediate children will be displayed.
2. dependencyGraphMaxDepth = 2, means nodes up to …

adding dependency graph depth controlling functionlity

---

modules/es-extensions/publisher/modules/greg-publisher-api.js

This fix is to filter out associations that are not with artifact type destination paths.

Fixing association page crash in publisher view

---

modules/es-extensions/publisher/extensions/app/greg_publisher/pages/greg-landing.jag

Concern - Users with add only permission for certain assets, they are not visible in landing page. This is due to adding an asset is inside the list view page. Because the user does not have list permission he can't navigate to that asset page. 
This will be fixed in 5.1.0 , since click on the asset type will redirects to the edit page.

REGISTRY-3018 Fix

---

modules/integration/tests-integration/tests-es/src/test/java/org/wso2/carbon/registry/es/utils/FileUploadWithAttachmentUtil.java

This util class uses ' org.apache.commons.httpclient.HttpClient' for file(wsdl,wadl,swagger,policy) upload.

Util class for file upload

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/asset.js
modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs

This PR is related to 
- wso2/carbon-store PR:https://github.com/wso2/carbon-store/pull/286
- wso2/carbon-store PR:https://github.com/wso2/carbon-store/pull/293
**Notification Change**:
This PR disables the ES notifications in the Governance Center.
*Note*: 
This PR introduces a notifications property the asset configuration:
```javascript
notifications :{
enabled:true
}
```
When TRUE all users with the admin role will be subscribed to lifecycle state change and asset updates. 
**Search Textbox Change**:
The search term entered by the user is persisted

Fix for STORE-1071 and Search query persistence

---

modules/es-extensions/store/asset/policy/asset.js
modules/es-extensions/store/asset/restservice/themes/store/partials/asset-download.hbs
modules/es-extensions/store/asset/swagger/themes/store/partials/asset-download.hbs
modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/copy-to-clipboard.js

- The copy to clipboard button is highlighted in yellow for a few seconds after the user clicks on it
- The download ,copy and swagger buttons now use the default button class

Style changes to the download and copy link buttons

---

modules/es-extensions/store/asset/policy/asset.js
modules/es-extensions/store/asset/restservice/asset.js
modules/es-extensions/store/asset/restservice/themes/store/partials/asset-download.hbs
modules/es-extensions/store/asset/soapservice/asset.js
modules/es-extensions/store/asset/swagger/asset.js
modules/es-extensions/store/asset/swagger/themes/store/partials/asset-download.hbs
modules/es-extensions/store/extensions/app/greg-store-defaults/asset.js
modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/asset-download.hbs

This PR has the following changes:
- The download link opens in a new tab
- The tenantId in the URL has been replaced by tenant(uses the tenant domain)
- The SOAPSERVICE asset type no longer shows the download link if there is no WSDL

Fixes REGISTRY-3232 and REGISTRY-3231

---

modules/es-extensions/publisher/asset/restservice/asset.js
modules/es-extensions/publisher/asset/soapservice/asset.js

This PR contains the following changes:
- Updated the SOAP and REST rxts to make the key fields readonly
Addresses the following issue: [REGISTRY-3028](https://wso2.org/jira/browse/REGISTRY-3028)

Fix for REGISTRY-3028

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/header.hbs

This PR changes the Go To Store link to be tenant aware. It will exhibit the following behaviour:
- Super tenant user : The link will not be tenant qualified (e.g. /store)
- Tenant user: The link will be tenant qualified (e.g. /store/t/wso2.com)
Addresses the issue: [REGISTRY-3323](https://wso2.org/jira/browse/REGISTRY-3323)

Fix for REGISTRY-3223

---

modules/es-extensions/store/asset/endpoint/asset.js
modules/es-extensions/store/asset/policy/asset.js
modules/es-extensions/store/asset/restservice/asset.js
modules/es-extensions/store/asset/schema/asset.js
modules/es-extensions/store/asset/soapservice/asset.js
modules/es-extensions/store/asset/swagger/asset.js
modules/es-extensions/store/asset/wadl/asset.js
modules/es-extensions/store/asset/wsdl/asset.js

This PR includes the following changes:
- The GREG asset extensions have been refactored to use the tenant-api provided by the ES Store
- This change ensures that the correct tenant's registry is used to retrieve assets
Addresses the following issue: [REGISTRY-3349](https://wso2.org/jira/browse/REGISTRY-3349)

Fix for REGISTRY-3349

---

modules/es-extensions/store/asset/restservice/themes/store/partials/asset-download.hbs
modules/es-extensions/store/asset/swagger/themes/store/partials/asset-download.hbs
modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/view-asset-diff-view-container.hbs
modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/view-asset-top-common-addons-container.hbs
modules/es-extensions/store/extensions/app/greg_impact/js/impactAnalysis.js
modules/es-extensions/store/extensions/app/greg_impact/pages/index.jag
modules/es-extensions/store/extensions/app/greg_swagger/pages/index.jag

This PR includes the following changes:
- Swagger UI and Impact View resources (css,js, and images) are now accessible via tenanted URLs
- Swagger UI and Dependency View buttons are constructed using tenanted URLs depending on how the page is accessed 
- If the details page is accessed using the tenanted URL the button links contain the tenant domain
Addresses the issue: [REGISTRY-3366](https://wso2.org/jira/browse/REGISTRY-3366)
Related PRs:
- https://github.com/wso2/carbon-store/pull/382

Fix for REGISTRY-3366

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/tags-container.js

This PR removes the placeholder from the select2 plugin initialization.There is a known issue with the placeholder and IE 11 which causes the select2 dropdown to appear after setting tags [2].The root cause of the issue is related to IE 11 behaviour related to input fields with placeholders [1]:
*It all comes down how IE11 manages placeholders. In IE11 when an input field is focused, the placeholder is removed, causing the input event to fire.*
The tag drop down appears due to the input event firing.
**Reference**
[1] https://connect.microsoft.com/IE/feedback/details/885747/ie-11-fires-the-input-event-when-a-input-field-with-placeholder-is-focused
[2] https://github.com/select2/select2/issues/3300
Addresses the issue: [REGISTRY-3338](https://wso2.org/jira/browse/REGISTRY-3338)

Fix for REGISTRY-3338

---

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs

This PR changes the tag rendering mechanism to use spans instead of labels.According the HTML specification anchor tags [1] cannot have interactive content [2].
*Reference*
[1] https://developer.mozilla.org/en/docs/Web/HTML/Element/a
[2] https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#interactive_content
This PR depends on: https://github.com/wso2/carbon-store/pull/400
Addresses the issue: [REGISTRY-3404](https://wso2.org/jira/browse/REGISTRY-3404)

Fix for REGISTRY-3404: Fix for tags 

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/tags-container.js

This PR adds a formatting method to prevent users from entering spaces.Any tag which is entered with spaces is converted to a - (dash) delimited phrase.
Addresses the issue: [REGISTRY-3343](https://wso2.org/jira/browse/REGISTRY-3343)

Fix for REGISTRY-3343

---

modules/es-extensions/store/asset/restservice/asset.js
modules/es-extensions/store/asset/soapservice/asset.js

Disabled the diff view for restservice and soapservice asset instances by using the isDiffViewEnabled property.
This property is by default set to true.
Addresses the following issue: [REGISTRY-3472](https://wso2.org/jira/browse/REGISTRY-3472)

Fix for REGISTRY-3472

---

modules/es-extensions/store/extensions/app/greg-diff-api/apis/governance-artifacts.jag
modules/es-extensions/store/extensions/app/greg-diff/themes/store/code/greg-diff-meta.hbs
modules/es-extensions/store/extensions/app/greg-diff/themes/store/helpers/diff-base.js
modules/es-extensions/store/extensions/app/greg-diff/themes/store/js/diff-api.js

This PR contains the following changes:
- The diff view API has been re-factored to utilize a tenant flow when loading diffs 
- The diff view API must be called with the tenant domain (if one is not provided it is assumed that the call is made for the carbon.super tenant domain)
- The client side scripts receive the tenant domain via the store.store.tenantDomain attribute
- The client side diff view code has been re-factored to support asynchronous loading 
Addresses the issue: [REGISTRY-3368](https://wso2.org/jira/browse/REGISTRY-3368)

Fix for REGISTRY-3368

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/notes-api.js

The use of location.relaod(true) twice makes it not appear in IE11 due to some page rendering issue.
Further the setTimeout method already calls the location.reload method. SO no point of calling it twice.
Therfore removed the additional location.reload method.

REGISTRY-3491 :  fix

---

modules/es-extensions/publisher/asset/swagger/themes/default/js/formatting.js
modules/es-extensions/store/asset/swagger/themes/store/js/formatting.js

This PR includes the following changes:
- Added license headers to the formatting plugin utilized by the CodeMirror library
- Added a reference to locate the said plugin
- Fixed an issue with the code snippet been selected
Addresses the issue: [REGISTRY-3457](https://wso2.org/jira/browse/REGISTRY-3457)

Fix for REGISTRY-3457

---

modules/es-extensions/publisher/extensions/app/greg_impact/js/impactAnalysis.js
modules/es-extensions/publisher/extensions/app/greg_impact/public/js/svgenie.js

With [1] user's can download the graph image in IE 10+.
With [2] downloaded image will contain the complete graph with the selected zoom level.
However the maximum size of the image downloadable may vary depending on the browser type.
[1] https://wso2.org/jira/browse/REGISTRY-3601
[2] https://wso2.org/jira/browse/REGISTRY-2961

improving G-Reg publisher dependency visualization feature

---

modules/distribution/src/main/resources/carbon-home/conf/registry.xml
modules/integration/tests-integration/tests-metadata/tests-metadata-generic/src/test/java/org/wso2/carbon/registry/metadata/test/restservice/RESTServiceCreationTestCase.java
modules/integration/tests-integration/tests-metadata/tests-metadata-generic/src/test/java/org/wso2/carbon/registry/metadata/test/restservice/RESTServiceUpdateTestCase.java
modules/integration/tests-integration/tests-metadata/tests-metadata-generic/src/test/resources/testng.xml

Test cases added to test the new RESTServiceMediaTypeHandler.
Also added the registry.xml entry to register the new handler.
Jira Issues
[REGISTRY-3532](https://wso2.org/jira/browse/REGISTRY-3532)
[REGISTRY-3577](https://wso2.org/jira/browse/REGISTRY-3577)
[REGISTRY-3579](https://wso2.org/jira/browse/REGISTRY-3579)

REGISTRY-3532, 3577, 3579 Improving Rest Service handling capability in Governance Center

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/tags-container.js

Making the tag select feature in asset edit page and the 'option' pane in GC consistent. 
Tag suggesting (for existing tags in the same type) functionality is added to 'option' pane which was missing.

Fix for REGISTRY-3587

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/lifecycle-rendering-view.hbs

This PR overrides the lifecycle-rendering-view.hbs provided the Store to ensure that the G-Reg permission model remains intact
Related to the following STORE JIRA: [STORE-1314](https://wso2.org/jira/browse/STORE-1314)
Related to the following STORE PR: https://github.com/wso2/carbon-store/pull/582

Fix for STORE-1314 

---

modules/distribution/src/main/resources/greg-migration-client/src/main/java/org/wso2/carbon/greg/migration/client/ProviderMigrationClient.java

Earlier, a registry put will be called on assets that did not have provider element as well.
Removed that behaviour. Now only assets which contain provider element in the metadata will be put again after modified.

Remove redundant registry put calls

---

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs

Highlighting tags belong to the asset in the GC Store; Asset Details page.

Fix for REGISTRY-3588

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/asset.js

This PR is related to [REGISTRY-3611](https://wso2.org/jira/browse/REGISTRY-3611)
Disabled 'auto' read-only configuration from `overview_provider` field in asset create page.

Fix for REGISTRY-3611

---

modules/es-extensions/store/extensions/app/greg-store-defaults/asset.js

PR related to [REGISTRY-3634](https://wso2.org/jira/browse/REGISTRY-3634)
Overriding sort attributes names in Greg side as overview_createdtime is not included in governance artifacts.

REGISTRY-3634 : Override sort attributes.

---

modules/es-extensions/store/extensions/app/greg-store-defaults/asset.js

Changed the timestamp attribute to createdDate
Depends on the following PR: https://github.com/wso2/carbon-store/pull/654
Addresses the following issue: [REGISTRY-3647](https://wso2.org/jira/browse/REGISTRY-3647)

Fix for REGISTRY-3647

---

modules/checkin-client/src/test/java/org/wso2/registry/checkin/util/BaseTestCase.java
modules/distribution/src/main/assembly/bin.xml
modules/distribution/src/main/resources/carbon-home/conf/security/Owasp.CsrfGuard.Carbon.properties
modules/p2-profile-gen/carbon.product
pom.xml

**Please do not merge this PR until carbon-kernel version is upgraded to 4.4.6. These test failures occurs only in kernel 4.4.6**

Fixing checkin client test failures for carbon-kernel 4.4.6 release

---

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/tag-cloud.hbs

Selected tags can be removed
Depends on the following PR: https://github.com/wso2/carbon-store/pull/739
Addresses the following issue: [REGISTRY-3726](https://wso2.org/jira/browse/REGISTRY-3726)

Fix for REGISTRY-3726

---

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs

In this PR:
* Remove unwanted CSS classes which overlap the search button.
Address the following issue : [REGISTRY-3813](https://wso2.org/jira/browse/REGISTRY-3813)

Fix for REGISTRY-3813: Remove unwanted bootstrap column classes

---

modules/samples/getting_started/src/org/wso2/carbon/registry/samples/populator/CategorizeArtifacts.java

This PR is related with [REGISTRY-3811](https://wso2.org/jira/browse/REGISTRY-3811)
Above issue is occurring because BuyMore assets do not have applied categories. To avoid confusion this PR modifies the sample populator to apply categories to BuyMore assets.

Populating categorization for BuyMore assets

---

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs
modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/tag-cloud.hbs

In this PR:
* Show tag cloud with relevant tags in asset detail page
Address the following issue: [REGISTRY-3819](https://wso2.org/jira/browse/REGISTRY-3819)
This PR **depends** on PR [#774](https://github.com/wso2/carbon-store/pull/774)

Fix for REGISTRY-3819 : Show asset related tag in asset details page

---

modules/samples/getting_started/src/org/wso2/carbon/registry/samples/populator/RXTModifier.java

In this PR:
* Fix the issue of creating an unintended collection named `permission` in the root directory of the registry.

Fix creating unintended collection in the registry root

---

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/css/common.css

Change the select2 field height to default value. It was change with association page changes, but this css property doesn't used in association dropdown. It uses below value,
/* Association page asset drop down */
span.select2-selection.select2-selection--single.select-resource {
height: 85px !important;
}
This value affects select2 dropdown in publisher create and update pages.

Revert select2 field height changes to default

---

modules/distribution/src/main/resources/carbon-home/conf/registry.xml

This fix is related to the following [1] red mine feature. [Enabling G-Reg/APIM Publisher and Store in separate cluster domains]
[1] - https://redmine.wso2.com/issues/4308

REGISTRY-3035 Fix - Add parameter to indexing configuration of registry.xml
