modules/integration/tests-integration/tests-extensibility/pom.xml
public jira: https://wso2.org/jira/browse/REGISTRY-2387
=> Excluding sl4j version conflicts in tests-extensibility

modules/integration/tests-integration/cmis-tck/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-extensibility/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-jiras/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-lifecycle/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-metadata/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-permissions/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-resources/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-samples/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-search-version/src/test/resources/axis2config/axis2_client.xml, modules/integration/tests-integration/tests-smoke/src/test/resources/axis2config/axis2_client.xml
public jira : https://wso2.org/jira/browse/REGISTRY-2388
=> Commenting TCPTransportSender from the axis2.xml and axis_client.xml in greg5 tests

modules/es-extensions/store/asset/service/themes/store/partials/asset.hbs, modules/es-extensions/store/asset/service/themes/store/partials/overview.hbs
According to ES structure, we should define all the asset description related overview data, in an overridden overview.hbs file, which is referred in the asset.hbs.
asset.hbs is related both asset description & user review data.
=> update the hbs files to view store

modules/distribution/src/main/resources/carbon-home/conf/master-datasources.xml
When start the G-Reg 5.0.0SNAPSHOT with mounting & -Dsetup, got the following error:
ERROR {org.wso2.carbon.social.sql.internal.SQLSocialComponent} -  
java.lang.NullPointerException
Inoreder to solve that updated our master-datasources.xml according to the ES master-datasource.xml
=> update the master-datasource.xml along with ES master-datasource.xml

modules/es-extensions/publisher/asset/service/themes/default/partials/view-asset.hbs, modules/es-extensions/publisher/asset/wsdl/themes/default/partials/view-asset.hbs, modules/jaggeryapps/greg-publisher/themes/default/css/es-publisher-commons.css, modules/jaggeryapps/greg-publisher/themes/publisher/css/es-publisher-commons.css, modules/jaggeryapps/greg-publisher/themes/service/css/es-publisher-commons.css
https://wso2.org/jira/browse/REGISTRY-2435
=> Moving css changes to HTML code

modules/es-extensions/publisher/asset/service/themes/default/partials/list_assets_table_body.hbs, modules/es-extensions/publisher/asset/service/themes/default/partials/view-asset.hbs
1.Pont to new cutomized thumnail image for service asset in publisher.
2.inteface wsdl url path should be intact.
3.Add table to show dependencies
=> add dependency view in service

modules/integration/tests-integration/cmis-tck/src/test/resources/automation.xml, modules/integration/tests-integration/tests-extensibility/src/test/resources/automation.xml, modules/integration/tests-integration/tests-governance-api/src/test/resources/automation.xml, modules/integration/tests-integration/tests-jiras/src/test/resources/automation.xml, modules/integration/tests-integration/tests-lifecycle/src/test/resources/automation.xml, modules/integration/tests-integration/tests-metadata/src/test/resources/automation.xml, modules/integration/tests-integration/tests-permissions/src/test/resources/automation.xml, modules/integration/tests-integration/tests-resources/src/test/resources/automation.xml, modules/integration/tests-integration/tests-samples/src/test/resources/automation.xml, modules/integration/tests-integration/tests-search-version/src/test/resources/automation.xml, modules/integration/tests-integration/tests-smoke/src/test/resources/automation.xml
https://wso2.org/jira/browse/REGISTRY-2438
=> Disabling coverage(emma) reports REGISTRY-2438

modules/integration/tests-common/ui-pages/src/main/java/org/wso2/greg/integration/common/ui/page/resourcebrowse/ResourceBrowsePage.java, modules/integration/tests-common/ui-pages/src/main/resources/mapper.properties, modules/integration/tests-ui-integration/tests-ui/src/test/java/org/wso2/carbon/greg/ui/test/lifecycle/LifeCycleFilterStatePersistenceTest.java
https://wso2.org/jira/browse/REGISTRY-2440
=> UI-test failure due to lifecycle improvements - REGISTRY-2440

modules/distribution/src/main/assembly/bin.xml, modules/es-extensions/publisher/asset/endpoint/themes/default/partials/view-asset.hbs, modules/es-extensions/publisher/asset/policy/themes/default/partials/view-asset.hbs, modules/es-extensions/publisher/asset/schema/themes/default/partials/view-asset.hbs, modules/es-extensions/publisher/asset/wadl/themes/default/partials/view-asset.hbs
1.Add API extension in publisher.
2.Add impact analysis links to assets in publisher.
=> add impact analysis

modules/integration/tests-integration/tests-metadata/src/test/java/org/wso2/carbon/registry/metadata/test/policy/NegativePolicyAdditionTestCase.java, modules/integration/tests-integration/tests-metadata/src/test/java/org/wso2/carbon/registry/metadata/test/policy/PolicyAddTestCase.java, modules/integration/tests-integration/tests-metadata/src/test/java/org/wso2/carbon/registry/metadata/test/policy/PolicyAdditionTestCase.java, modules/integration/tests-integration/tests-metadata/src/test/java/org/wso2/carbon/registry/metadata/test/policy/PolicyDeleteTestCase.java, modules/integration/tests-integration/tests-metadata/src/test/java/org/wso2/carbon/registry/metadata/test/wadl/AddWADLTestCase.java
https://wso2.org/jira/browse/REGISTRY-2466
=> Adding dependsOnMethods to @Test annotation - tests-metadata

modules/distribution/src/main/resources/carbon-home/conf/registry.xml
https://wso2.org/jira/browse/REGISTRY-2469
=> Correcting the registry.xml endpoint mediatype - REGISTRY-2469

modules/integration/tests-integration/tests-metadata/src/test/java/org/wso2/carbon/registry/metadata/test/wsdl/ValidWsdlWithEndpointsTestCase.java, modules/integration/tests-integration/tests-metadata/src/test/resources/artifacts/GREG/apptestresources/registry.xml, modules/integration/tests-integration/tests-search-version/src/test/java/org/wso2/carbon/registry/mediatype/test/HumanReadableMediaTypeTest.java, modules/integration/tests-integration/tests-search-version/src/test/java/org/wso2/carbon/registry/mediatype/test/RegistrySearchMediaType.java, modules/integration/tests-integration/tests-search-version/src/test/java/org/wso2/carbon/registry/service/search/test/SearchDependentEndpointInWsdlTestCase.java, modules/integration/tests-integration/tests-search-version/src/test/resources/testng.xml
https://wso2.org/jira/browse/REGISTRY-2470
=> Integration tests for Endpoint mediatype display - REGISTRY-2470

modules/distribution/src/main/assembly/bin.xml, modules/distribution/src/main/resources/carbon-home/conf/identity.xml, modules/es-extensions/publisher/extensions/app/greg_publisher/app.js, modules/es-extensions/store/extensions/app/greg_store/app.js, modules/integration/tests-integration/tests-metadata/src/test/resources/testng.xml, modules/p2-profile-gen/pom.xml
https://wso2.org/jira/browse/REGISTRY-2476
=> Removing APIM related features from greg.

modules/distribution/src/main/assembly/bin.xml, modules/es-extensions/publisher/extensions/app/greg_publisher/app.js, modules/es-extensions/store/extensions/app/greg_store/app.js, modules/integration/tests-integration/tests-metadata/src/test/resources/testng.xml, modules/p2-profile-gen/pom.xml
Fix for the local test fail due to multiple threads
=> Testcase fix for Resource(WSDL/WADL/Schema/Policy) upload path change

modules/es-extensions/publisher/asset/soapservice/asset.js
=> Fix for Jira https://wso2.org/jira/browse/STORE-683

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/css/sidepanel.css, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/sidepanel.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/ribbon.hbs, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/sidebar-container.hbs
=> Added notification view to side toggle panel + some style tweaks

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/css/sidepanel.css, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/notifications-container.hbs
Please merge this PR which contains a file, which is missing in the earlier PR
=> Added notifications-container.hbs + some minor style fixes

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/asset.js
=> Minor fix on app-bar: Added "Associations" button to necessary pages

modules/distribution/src/main/resources/carbon-home/conf/identity.xml
https://wso2.org/jira/browse/REGISTRY-2529
=> Updating identity.xml according to APIM, adding ClientAuthHandlers

modules/es-extensions/store/asset/restservice/themes/store/partials/asset-details.hbs, modules/es-extensions/store/asset/schema/themes/store/partials/asset-details.hbs, modules/es-extensions/store/asset/soapservice/themes/store/partials/asset-details.hbs, modules/es-extensions/store/asset/swagger/themes/store/partials/asset-details.hbs, modules/es-extensions/store/asset/wadl/themes/store/partials/asset-details.hbs, modules/es-extensions/store/asset/wsdl/themes/store/partials/asset-details.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/css/asset-styles.css, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/helpers/asset.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/asset-details.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/asset-utilization.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/asset.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/share.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/social-buttons.hbs
Please review and merge
TODO: override related actions for buttons...ions/store/extensions/app/greg-store-defaults/themes/store/partials/asset-utilization.hbs
=> asset details customization for g-reg

modules/p2-profile-gen/pom.xml
Removing identity provider and service provider
=> Fix for REGISTRY-2417 and REGISTRY-2418 

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/header.hbs, modules/es-extensions/sso/jaggery.conf, modules/es-extensions/sso/views/themes/theme-greg/css/custom.css, modules/es-extensions/sso/views/themes/theme-greg/includes/header.jag, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/css/common.css, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/helpers/header.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/header.hbs
Please review and merge the PR which contains $title
=> [REGISTRY-2611] & [REGISTRY-2608] Fixes

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/css/common.css, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/sidepanel.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/pages/2-column-right.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/header.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs
Fixed nav affix, notification panel style & some related style issues
=> [REGISTRY-2623] - Fix

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/css/common.css
Please merge the PR which contains $title
=> Added switch toggle style

modules/samples/handler/src/pom.xml
Added a package to sample pom file
=> Fix for G-Reg Sample - Scheduled Task

modules/samples/asset-models/Populator/build.xml
Changed build.xml of the sample
=> Fix for asset models sample

modules/es-extensions/publisher/asset/swagger/themes/default/helpers/view-asset.js, modules/es-extensions/publisher/asset/swagger/themes/default/js/formatting.js, modules/es-extensions/publisher/asset/swagger/themes/default/js/javascript.js, modules/es-extensions/publisher/asset/swagger/themes/default/js/view-asset.js
Please review & merge the PR which contains $title
=> Fixed: Swagger JSON formatting

modules/distribution/src/main/assembly/bin.xml, modules/samples/handler/src/pom.xml, modules/samples/search-client/src/org.wso2.carbon.registry.search.client/build.xml, modules/samples/search-client/src/org.wso2.carbon.registry.search.client/src/main/java/org/wso2/carbon/registry/search/client/SearchClient.java
Exported the relevant package in the sample pom.xml file
=> Fix for G-Reg samples (Custom report sample, Query Processor Sample, Notification E-mail Customization Sample)

modules/es-extensions/publisher/extensions/app/greg_impact/css/style.css, modules/es-extensions/publisher/extensions/app/greg_impact/js/impactAnalysis.js, modules/es-extensions/publisher/extensions/app/greg_impact/pages/index.jag
[1] https://wso2.org/jira/browse/REGISTRY-2744
[2] https://wso2.org/jira/browse/REGISTRY-2745
=> fixing REGISTRY-2745 and REGISTRY-2744

modules/distribution/pom.xml
[1] https://wso2.org/jira/browse/IDENTITY-3489
=> work around to mitigate effects of IDENTITY-3489

modules/samples/asset-models/ApplicationModel/pom.xml, modules/samples/asset-models/BusinessProcessModel/pom.xml, modules/samples/asset-models/PeopleModel/pom.xml, modules/samples/asset-models/ProjectModel/pom.xml, modules/samples/asset-models/TestPlanModel/pom.xml
[1] https://wso2.org/jira/browse/REGISTRY-2115
=> correcting parent references in asset-model pom.xml files

modules/es-extensions/publisher/extensions/app/greg_publisher/app.js, modules/es-extensions/publisher/extensions/app/greg_publisher/pages/password.jag, modules/es-extensions/publisher/extensions/app/greg_publisher/themes/default/helpers/password.js, modules/es-extensions/publisher/extensions/app/greg_publisher/themes/default/js/validate.js, modules/es-extensions/publisher/extensions/app/greg_publisher/themes/default/pages/add-list-password.hbs, modules/es-extensions/publisher/extensions/app/greg_publisher/themes/default/renderers/pages/password.js, modules/es-extensions/publisher/modules/greg-publisher-api.js, modules/p2-profile-gen/pom.xml
This is an improvement to add encrypted properties at the Governance - Publisher
=> Property Encryption Page - Publisher

modules/es-extensions/publisher/asset/policy/asset.js, modules/es-extensions/publisher/asset/schema/asset.js, modules/es-extensions/publisher/asset/swagger/asset.js, modules/es-extensions/publisher/asset/wadl/asset.js, modules/es-extensions/publisher/asset/wsdl/asset.js
Unable to add tags to Policies, Schemas, Swaggers, WADLs and WSDLs from publisher end'
=> REGISTRY-2786 - Fiexd issue 'Unable to add tags to some assets in publisher end.'

modules/es-extensions/publisher/extensions/app/greg_impact/css/style.css
FIXED - Locate asset functionality in Dependency graph is not working
=> [REGISTRY-2752] - FIX

modules/es-extensions/publisher/modules/greg-publisher-api.js
[1] https://wso2.org/jira/browse/REGISTRY-2823
=> fixing REGISTRY-2823

modules/es-extensions/publisher/asset/policy/asset.js, modules/es-extensions/publisher/asset/schema/asset.js, modules/es-extensions/publisher/asset/wadl/asset.js, modules/es-extensions/publisher/asset/wsdl/asset.js
[1] https://wso2.org/jira/browse/REGISTRY-2965
=> artifact name and version are not displayed in advanced search results

modules/es-extensions/publisher/extensions/app/greg_impact/js/impactAnalysis.js, modules/es-extensions/publisher/extensions/app/greg_impact/pages/index.jag
a message will be shown indicating that particular asset type is not activated for publisher view
[1] https://wso2.org/jira/browse/REGISTRY-2978
=> disabled double clicking for inactivated assets

modules/es-extensions/publisher/asset/swagger/asset.js
[1] https://wso2.org/jira/browse/REGISTRY-2967
=> Fixing to render swagger advanced search results correctly

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs
Remove duplication of notificatoin icon in asset detail view of store
=> Remove duplication of notificatoin icon in detail view of store

modules/es-extensions/publisher/modules/greg-publisher-api.js, modules/es-extensions/store/modules/greg-publisher-api.js
Fix for https://wso2.org/jira/browse/REGISTRY-3058
=> Resolving error given when one artifact with notification is deleted

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/header.hbs
[1] https://wso2.org/jira/browse/REGISTRY-2991
=> REGISTRY-2991 - moving go to store link to a separate div

pom.xml
carbon-registry, carbon-governance, carbon-governance-extensions, carbon-commons, carbon-multitenancy, jaggery, and jaggery-extensions
=> updating repo versions

modules/es-extensions/publisher/modules/greg-publisher-api.js, modules/es-extensions/store/modules/greg-publisher-api.js
Fix for https://wso2.org/jira/browse/REGISTRY-3059
=> display notifications done on collections at publisher and store side

modules/es-extensions/publisher/extensions/app/greg_publisher/themes/default/partials/gc-landing.hbs
[1] https://wso2.org/jira/browse/REGISTRY-3075
=> REGISTRY-3075 - permisson check for service add blocks

modules/es-extensions/publisher/modules/greg-publisher-api.js, modules/es-extensions/store/modules/greg-publisher-api.js
Fix for https://wso2.org/jira/browse/REGISTRY-3101
=> REGISTRY-3101 Fix

modules/es-extensions/publisher/asset/soapservice/asset.js, modules/integration/tests-integration/tests-es/src/test/java/org/wso2/carbon/registry/es/publisher/crud/GenericCRUDTestCase.java
=> Revert "Integration test hackthone"

modules/integration/tests-integration/tests-es/src/test/java/org/wso2/carbon/registry/es/governancresteapi/GovernanceRestAPITestCase.java
provide test cases for asset creation, asset listing, get all asset types, get asset by uuid
=> Update governance rest api test cases

modules/es-extensions/store/asset/policy/themes/store/partials/asset-code-view.hbs, modules/es-extensions/store/asset/restservice/themes/store/partials/asset-code-view.hbs, modules/es-extensions/store/asset/schema/themes/store/partials/asset-code-view.hbs, modules/es-extensions/store/asset/soapservice/themes/store/partials/asset-code-view.hbs, modules/es-extensions/store/asset/swagger/themes/store/partials/asset-code-view.hbs, modules/es-extensions/store/asset/wadl/themes/store/partials/asset-code-view.hbs, modules/es-extensions/store/asset/wsdl/themes/store/partials/asset-code-view.hbs
[1] https://wso2.org/jira/browse/REGISTRY-3105
=> REGISTRY-3105 - adding links to down load raw content

modules/integration/tests-integration/tests-extensibility/tests-search/src/test/java/org/wso2/carbon/registry/search/tags/test/TagsSearchTestCase.java, modules/integration/tests-integration/tests-metadata/tests-metadata-generic/src/test/java/org/wso2/carbon/registry/metadata/test/custom/AddRxtTest.java, modules/integration/tests-integration/tests-resources/tests-resource-registry/src/test/java/org/wso2/greg/integration/resources/resource/test/CollectionAssociationsTestCase.java, modules/integration/tests-integration/tests-resources/tests-resource-social/src/test/java/org/wso2/greg/integration/resources/resource/test/ResourceAssociationsTestCase.java
fixing test modules - resources, metadata and sensibility relating to REGISTRY-3080 null value check
=> REGISTRY-3080 - fixing tests

modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/test/CheckMandatoryFieldsTestCase.java, pom.xml
And this PR contains test case to verify 	REGISTRY-3080 fix
=> updating jaggery extensions feature versions to 1.4.5-SNAPSHOT

modules/es-extensions/publisher/modules/greg-publisher-api.js
[1] https://wso2.org/jira/browse/REGISTRY-3174
=> REGISTRY-3174 - fixing crash in association page

modules/es-extensions/publisher/extensions/app/greg-associations/themes/default/css/association-base.css, modules/es-extensions/publisher/extensions/app/greg-associations/themes/default/js/association-api.js, modules/es-extensions/publisher/extensions/app/greg-associations/themes/default/partials/association-entry.hbs, modules/es-extensions/publisher/modules/greg-publisher-api.js, modules/integration/tests-integration/tests-es/src/test/java/org/wso2/carbon/registry/es/utils/GregESTestBaseTest.java
[1] https://wso2.org/jira/browse/REGISTRY-3165
=> REGISTRY-3165 - Version Details are not populated when browsed to associations tab of an asset

modules/es-extensions/common/extensions/app/greg_impact/modules/dataPopulator.js, modules/es-extensions/common/extensions/app/greg_impact/pages/index.jag
=> REGISTRY-3234 - fix for tenants to see the dependency graph

modules/es-extensions/store/asset/endpoint/themes/store/partials/asset.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/asset.hbs
This PR is related to: https://github.com/wso2/carbon-store/pull/328
Relevant Issue: [STORE-1186](https://wso2.org/jira/browse/STORE-1186)
=> Migrated review functionality of asset extensions to use social-reviews app extension implementation

modules/integration/tests-ui-integration/pom.xml, modules/integration/tests-ui-integration/tests-es-ui/pom.xml
Updating test-ui-integration to version 5.2.0
=> Updating test-ui-integration to version 5.2.0

modules/distribution/src/main/resources/greg-migration-client/pom.xml, modules/distribution/src/main/resources/greg-migration-client/src/main/java/org/wso2/carbon/greg/migration/client/ProviderMigrationClient.java, modules/distribution/src/main/resources/greg-migration-client/src/main/java/org/wso2/carbon/greg/migration/client/internal/GRegMigrationServiceComponent.java, modules/distribution/src/main/resources/greg-migration-client/src/main/java/org/wso2/carbon/greg/migration/util/Constants.java
Migration tool to remove "provider" attribute from all existing governance assets.
=> REGISTRY-3189 adding migration tool

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/sidepanel.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/sidepanel.js
Removed some white-spaces as well.
=> REGISTRY-3369 fix , change arrow heading on collapse

modules/samples/pom.xml, pom.xml
=> updating registry, governance and governance-ext versions in root pom and samples pom.xml

modules/distribution/src/main/assembly/bin.xml, modules/p2-profile-gen/pom.xml, pom.xml
In this PR I have:
- Add carbon-metrics feature to Greg
- Add carbon-metrics jaggery module to p2-profile-gen
**IMPORTANT**: 
- This PR is depends on following STORE PR:  https://github.com/wso2/carbon-store/pull/416
=> Feature: Carbon Metrics Intergration

modules/es-extensions/publisher/asset/policy/themes/default/js/view-asset.js, modules/es-extensions/publisher/asset/schema/themes/default/js/view-asset.js, modules/es-extensions/publisher/asset/swagger/themes/default/js/view-asset.js, modules/es-extensions/publisher/asset/wadl/themes/default/js/view-asset.js, modules/es-extensions/publisher/asset/wsdl/themes/default/js/view-asset.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/diff-view.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/view-asset-diff-view-container.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/diff-view.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/view-asset-diff-view-container.hbs
add asset type to `compare with` button <i>href<i> dynamically
=> Fix for Registry 3438: send asset type in diff-view api call dynamically

modules/es-extensions/publisher/asset/restservice/themes/default/partials/update_asset.hbs, modules/es-extensions/publisher/asset/soapservice/themes/default/partials/update_asset.hbs, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/update_asset.hbs, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/view-asset-top-common-container.hbs
This PR aligns the title,version and state with thumbnail.
Addresses the issue: [REGISTRY-3505](https://wso2.org/jira/browse/REGISTRY-3505)
=> Fix for REGISTRY-3505

modules/distribution/pom.xml, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/footer.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/footer.hbs
The product version will be copied to the publisher.json and store.json at build time, using the replace file command given in the distribution pom file.
=> REGISTRY-3466 - add greg version to the footer

modules/es-extensions/publisher/asset/policy/themes/default/partials/create_form.hbs, modules/es-extensions/publisher/asset/policy/themes/default/partials/view-asset-details-container.hbs, modules/es-extensions/publisher/asset/schema/themes/default/partials/create_form.hbs, modules/es-extensions/publisher/asset/schema/themes/default/partials/view-asset-details-container.hbs, modules/es-extensions/publisher/asset/swagger/themes/default/partials/create_form.hbs, modules/es-extensions/publisher/asset/swagger/themes/default/partials/view-asset-details-container.hbs, modules/es-extensions/publisher/asset/wadl/themes/default/partials/create_form.hbs, modules/es-extensions/publisher/asset/wadl/themes/default/partials/view-asset-details-container.hbs, modules/es-extensions/publisher/asset/wsdl/themes/default/partials/create_form.hbs, modules/es-extensions/publisher/asset/wsdl/themes/default/partials/view-asset-details-container.hbs
**Changes**
- Left aligns all labels across the create,update and details pages.
- Adds the custom-form-label class to all labels
Addresses the following issue: [REGISTRY-3529](https://wso2.org/jira/browse/REGISTRY-3529)
=> Fix for REGISTRY-3529

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/greg-subscriptions-api.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/notifications-container.hbs
Addresses the following issue: [REGISTRY-3534](https://wso2.org/jira/browse/REGISTRY-3534)
=> Fix for REGISTRY-3534

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/greg-subscriptions-api.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/greg-subscriptions-api.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/pages/2-column-right.hbs
This PR depends on https://github.com/wso2/carbon-store/pull/461
Addresses the following issue: [REGISTRY-3540](https://wso2.org/jira/browse/REGISTRY-3540)
=> Fix for REGISTRY-3540

modules/distribution/src/main/resources/carbon-home/conf/registry.xml
adding taxonomy  handler to registry.xml
=> adding taxonomy  handler to registry.xml

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/code/taxonomy-tenant-meta.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/helpers/header.js
=> Revert "adding taxonomy-meta to header"

modules/es-extensions/publisher/extensions/app/greg_impact/js/impactAnalysis.js, modules/es-extensions/store/extensions/app/greg_impact/js/impactAnalysis.js, modules/es-extensions/store/extensions/app/greg_impact/public/js/svgenie.js
[1] https://wso2.org/jira/browse/REGISTRY-3601
[2] https://wso2.org/jira/browse/REGISTRY-2961
=> improving G-Reg store dependency visualization feature

modules/es-extensions/publisher/extensions/app/greg_impact/js/impactAnalysis.js, modules/es-extensions/publisher/extensions/app/greg_impact/public/js/svgenie.js, modules/es-extensions/store/extensions/app/greg_impact/js/impactAnalysis.js, modules/es-extensions/store/extensions/app/greg_impact/public/js/svgenie.js
[1] https://wso2.org/jira/browse/REGISTRY-3604
=> fixing dependency graph image not downloading for Safari 

modules/es-extensions/publisher/extensions/app/greg_impact/js/impactAnalysis.js, modules/es-extensions/store/extensions/app/greg_impact/js/impactAnalysis.js
[1] https://wso2.org/jira/browse/REGISTRY-3608
=> REGISTRY-3608 - fitting the created graph to the screen on page load

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/asset.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/css/common.css
PR related with [REGISTRY-3637](https://wso2.org/jira/browse/REGISTRY-3637)
Overridden `tab-selected` css class and changed the `iconClass` of navbar buttons Associations and Permissions
=> Fix for REGISTRY-3637

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/css/common.css
This PR is related with [REGISTRY-3635](https://wso2.org/jira/browse/REGISTRY-3635)
This PR includes styling changes to resolve UI issues of the Governance Center asset search box.
=> REGISTRY-3635 : Fixing GC searchbox UI

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/css/common.css, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/sidepanel.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/pages/2-column-right.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs
=> adding multiple taxonomy

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs
Wrapping categorization-entry partial in a div.
=> Categorization feature - Revised changes

modules/es-extensions/publisher/extensions/app/greg-associations/themes/default/js/association-api.js, modules/es-extensions/publisher/modules/greg-publisher-api.js
Currently alert messages shows in the similar way. We have added the Jira [1] to track this.
[1] - https://wso2.org/jira/browse/REGISTRY-3642
=> REGISTRY-3425 Fix : Proper handling of adding existing associations

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/taxonomy-overview.hbs
This PR includes changes done to the taxonomy-overview.hbs to display taxonomies applied to an asset.
=> Taxonomy overview partial changes

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/asset.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/list-assets.hbs
In this PR:
*  Update the `list-assets` partial with dynamic sorting attributes
Address the following issue : [REGISTRY-3650](https://wso2.org/jira/browse/REGISTRY-3650)
=> Fix for REGISTRY-3650 : Update list asset partial

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/pages/2-column-right.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/navigation.hbs
REGISTRY-3666 solving governance center UI issues
=> REGISTRY-3666 solving governance center UI issues

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/taxonomy-overview.hbs
Adding a custom CSS class to taxonomy view container in asset overview page.
=> Fix UI issue in taxonomy view in asset overview page

modules/es-extensions/publisher/extensions/app/greg-diff/themes/default/pages/diff-view-base.hbs, modules/es-extensions/publisher/extensions/app/greg_impact/pages/index.jag, modules/es-extensions/publisher/extensions/app/greg_swagger/pages/index.jag, modules/es-extensions/store/extensions/app/greg-diff/themes/store/pages/diff-view-base.hbs, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/pages/2-column-right.hbs, modules/es-extensions/store/extensions/app/greg_impact/pages/index.jag, modules/es-extensions/store/extensions/app/greg_swagger/pages/index.jag
*Note* Do NOT merge
This PR adds the csrf.js script to any new pages and page templates added via app extensions.
This PR depends on the the follwing carbon-store PR:https://github.com/wso2/carbon-store/pull/644
=> Fix csrf vulnerabilities

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/css/typeahead.css
https://wso2.org/jira/browse/REGISTRY-3719
=> Fixing search history dropdown position

modules/es-extensions/publisher/modules/greg-publisher-api.js
resolve publisher permission model, Assets visible to public selected for newly created assets .
=> REGISTRY-3615 resolve publisher permision model assets visible to public

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/pages/2-column-right.hbs
adding taxonomy missing style for white button
=> adding taxonomy missing style for white button

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/css/common.css, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/sidepanel.js
Removes CSS and JS whch have been moved to the carbon-store.
Related to the following issue [STORE-1391](https://wso2.org/jira/browse/STORE-1391)
=> Sibling commit to fix STORE-1391

modules/samples/getting_started/src/org/wso2/carbon/registry/samples/populator/Main.java
Fixing https://wso2.org/jira/browse/REGISTRY-3798
=> Adding version property for schemas

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/tag-cloud.hbs
This PR is dependent on the following PRs:
- https://github.com/wso2/carbon-store/pull/758
Addresses the following issues:
- [REGISTRY-3657](https://wso2.org/jira/browse/REGISTRY-3657)
- [REGISTRY-3781](https://wso2.org/jira/browse/REGISTRY-3781)
=> Fix for REGISTRY-3781 and REGISTRY-3657

modules/es-extensions/store/extensions/app/greg-store-defaults/asset.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/asset-attributes.hbs
In this PR:
* Add new dependency check flags 
Address the following issue : [REGISTRY-3740](https://wso2.org/jira/browse/REGISTRY-3740)
=> Fix for REGISTRY-3740 : Hide empty association entries

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/css/common.css, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/greg-subscriptions-api.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/css/common.css, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/greg-subscriptions-api.js
Changed the store notification clear all conformation box to align with publisher one
=> REGISTRY-3822 - fix for -  Align notification clear all message icon with the message.

modules/es-extensions/publisher/extensions/app/soap-viewer/modules/wsdl-api.js, modules/es-extensions/publisher/extensions/app/soap-viewer/pages/wsdl-viewer.jag, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/partials/view-asset-top-common-button-group.hbs, modules/es-extensions/store/extensions/app/soap-viewer/modules/wsdl-api.js, modules/es-extensions/store/extensions/app/soap-viewer/pages/wsdl-viewer.jag, pom.xml
Support WSDL visualization with tenant anonymous user.
=> REGISTRY-3832 fix

modules/samples/getting_started/src/org/wso2/carbon/registry/samples/populator/RXTModifier.java
In this PR:
* Change related to the previous PR  #820
=> Make path relative to governance regisrty location

modules/checkin-client/pom.xml, modules/distribution/pom.xml, modules/distribution/src/main/assembly/bin.xml, modules/distribution/src/main/resources/carbon-home/conf/user-mgt.xml, modules/distribution/src/main/resources/greg-migration-client/pom.xml, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/lifecycle-rendering-view.hbs, modules/integration/tests-common/admin-clients/pom.xml, modules/integration/tests-common/integration-test-utils/pom.xml, modules/integration/tests-common/platform-tests-utils/pom.xml, modules/integration/tests-integration/tests-extensibility/tests-capp/pom.xml, modules/integration/tests-integration/tests-extensibility/tests-discovery/pom.xml, modules/integration/tests-integration/tests-extensibility/tests-report/pom.xml, modules/integration/tests-integration/tests-extensibility/tests-search/pom.xml, modules/integration/tests-integration/tests-extensibility/tests-utf-support/pom.xml, modules/integration/tests-integration/tests-extensibility/tests-xpath/pom.xml, modules/integration/tests-integration/tests-governance-api/pom.xml, modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/lifecycle/test/GovernanceLCTransitionsTestCase.java, modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/test/GenericGovernanceArtifactTestCase.java, modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/test/PolicyManagerAPITestCase.java, modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/test/SchemaManagerAPITestCase.java, modules/integration/tests-integration/tests-governance-api/src/test/resources/testng.xml, modules/p2-profile-gen/carbon.product, modules/p2-profile-gen/pom.xml, modules/samples/pom.xml, pom.xml
=> Update kernel, identity, governance and registry versions

modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/partials/copy-asset.hbs
=> Add message to say new version creates, is a shallow copy

modules/es-extensions/publisher/extensions/app/greg-diff-api/app.js, modules/es-extensions/publisher/extensions/app/greg-diff-api/modules/governance-diff-api.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/asset.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/themes/default/js/diff-view.js, modules/es-extensions/publisher/extensions/app/greg_swagger/pages/index.jag, modules/es-extensions/store/extensions/app/greg-diff-api/app.js, modules/es-extensions/store/extensions/app/greg-diff/themes/store/css/diff.css, modules/es-extensions/store/extensions/app/greg-store-defaults/asset.js, modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/js/diff-view.js, modules/es-extensions/store/extensions/app/greg_swagger/app.js, modules/es-extensions/store/extensions/app/greg_swagger/modules/utility.js, modules/es-extensions/store/extensions/app/greg_swagger/pages/index.jag, modules/es-extensions/store/modules/greg-publisher-api.js
In this PR:
I have fixed the issues commented inline in the previous PRs,
Please find the commit message for relevant comment ID.
Thanks
=> Fix for: Previous PRs issues mentioned in inline commets

modules/es-extensions/publisher/extensions/app/greg-apis/app.js, modules/es-extensions/publisher/extensions/app/greg-associations/app.js, modules/es-extensions/publisher/extensions/app/greg-publisher-defaults/asset.js
=> Fix authorization issue in publisher association page

modules/integration/tests-ui-integration/tests-es-ui/src/test/java/org/wso2/carbon/greg/publisher/crudui/CustomRestRXTTestCase.java, modules/integration/tests-ui-integration/tests-es-ui/src/test/resources/artifacts/GREG/rxt/customRest.rxt, modules/integration/tests-ui-integration/tests-es-ui/src/test/resources/artifacts/GREG/rxt/defaultRest.rxt, modules/integration/tests-ui-integration/tests-es-ui/src/test/resources/testng.xml
This is related to fix : https://github.com/wso2/carbon-store/pull/848
Public jira for this: https://wso2.org/jira/browse/REGISTRY-3896
=> Added test case for REGISTRY-3896 fix

modules/integration/tests-integration/tests-metadata/tests-metadata-generic/src/test/java/org/wso2/carbon/registry/metadata/test/restservice/RESTServiceCreationTestCase.java, modules/integration/tests-integration/tests-metadata/tests-metadata-generic/src/test/java/org/wso2/carbon/registry/metadata/test/restservice/RESTServiceUpdateTestCase.java
This PR includes improvements suggested by reviews.
=> Fix for improvements suggested in reviews

modules/es-extensions/store/extensions/app/greg-store-defaults/themes/store/helpers/header.js, modules/integration/tests-ui-integration/tests-es-ui/src/test/java/org/wso2/carbon/greg/publisher/lifecycles/CustomLifecycleUITestCase.java, modules/integration/tests-ui-integration/tests-es-ui/src/test/java/org/wso2/carbon/greg/test/controller/Controller.java
updating PR comment suggestions
=> Update PRs comment suggestions

modules/integration/tests-common/admin-clients/pom.xml, modules/integration/tests-common/admin-clients/src/main/java/org.wso2.greg.integration.common.clients/LoggingAdminClient.java, modules/integration/tests-integration/tests-resources/tests-resource-registry/src/test/java/org/wso2/greg/integration/resources/resource/test/IndexFromNoCacheTestCase.java, modules/integration/tests-integration/tests-resources/tests-resource-registry/src/test/java/org/wso2/greg/integration/resources/server/mgt/test/RegistryConfiguratorTestCase.java, pom.xml
This integration tests are related to the following PRs [1],[2], [3] and red mine feature [4].
[1] - https://github.com/wso2/carbon-registry/pull/115
[2] - https://github.com/wso2/product-greg/pull/223
[3] - https://github.com/wso2/carbon-kernel/pull/550
[4] - https://redmine.wso2.com/issues/4308
=> REGISTRY-3035 - Add Integration tests

modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/rest/test/GovernanceRESTAPITestCase.java, modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/rest/test/HTTPSClientUtils.java, modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/rest/test/HttpResponse.java, modules/integration/tests-integration/tests-governance-api/src/test/resources/testng.xml
This includes the test cases to test governance REST API
This test included an unbounded table payload POST and a GET
=> Add integration tests for governace REST API.

modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/rest/test/HTTPSClientUtils.java, modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/rest/test/ResponseValidatorTestCase.java, pom.xml
Test cases for fixing REST API GET response json has two 'type' parameters
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
Fixes for REST API GET response json has two 'type' parameters
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the …
=> Fixes for REST API GET response json has two 'type' parameters

modules/integration/tests-integration/tests-governance-api/src/test/java/org/wso2/carbon/registry/governance/api/rest/test/GovernanceRESTAPITestCase.java
>Add integrations tests to test REGISTRY-3936.
=> Add integrations tests to test REGISTRY-3936.

modules/dashboard/pom.xml, modules/distribution/src/main/resources/greg-migration-client/pom.xml, modules/integration/tests-common/test-artifacts/backwardAssociationHandler/pom.xml, modules/integration/tests-integration/tests-samples/src/test/resources/artifacts/GREG/populate/FooModel/pom.xml, modules/login/pom.xml, modules/samples/asset-models/ApplicationModel/pom.xml, modules/samples/asset-models/BusinessProcessModel/pom.xml, modules/samples/asset-models/PeopleModel/pom.xml, modules/samples/asset-models/ProjectModel/pom.xml, modules/samples/asset-models/TestPlanModel/pom.xml, modules/samples/custom-ui/src/org.wso2.carbon.registry.samples.custom.topics.ui/pom.xml, modules/samples/custom-ui/src/org.wso2.carbon.registry.samples.custom.topics/pom.xml, modules/samples/handler/src/pom.xml, modules/samples/jcr-client/src/org.wso2.carbon.registry.jcr.client/pom.xml, modules/samples/search-client/src/org.wso2.carbon.registry.search.client/pom.xml, modules/samples/shutterbug/src/org.wso2.carbon.governance.samples.shutterbug.ui/pom.xml, modules/samples/shutterbug/src/org.wso2.carbon.governance.samples.shutterbug/pom.xml, modules/samples/taggingHandler/src/pom.xml, modules/styles/dashboard/pom.xml, modules/styles/product/pom.xml, modules/styles/service/pom.xml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Updated maven-bundle-plugin version to 2.5.4.
